--THE PURPOSE OF THIS FILE IS TO GIVE YOU ALL DATABASE INFORMATION AND THE QUERIES I USED TO BUILD IT.
--EVERYTHING BUILT USING THE PGADMIN CLIENT. NO COMMAND LINE OR PSQL EVER USED IN THIS PROJECT


CREATE DATABASE userdb

CREATE TABLE users (
user_name varchar,
user_email varchar,
user_password varchar,
user_role varchar
);